import { ICard } from '../types/types';

const cards: ICard[] = [
    {
        title: 'SHIRT WITH DECORATIVE DETAILS ON THE COLLAR',
        color: ['KHAKI'],
        image: 'assets/images/light-khaki-shirt.jpg',
        description: 'Cotton shirt with collar and beads. Long sleeves, slits at the bottom. Fastens with buttons.',
        category: 'shirts',
        price: '59.99 USD',
        size: ['XS', 'S', 'M', 'L', 'XL'],
        brand: 'MANGO',
        quantity: 20,
        year: 2020,
        popular: true,
        id: 1,
    },
    {
        title: 'CROPPED SHIRT WITH GLOSSY SHINE',
        color: ['KHAKI'],
        image: 'assets/images/neon-lime-shirt.jpg',
        description:
            'Shirt with turn-down collar and V-neck. Long sleeves with cuffs. It fastens with buttons and ties at the front.',
        category: 'shirts',
        price: '79.99 USD',
        size: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
        brand: 'ZARA',
        quantity: 10,
        year: 2021,
        popular: true,
        id: 2,
    },
    {
        title: 'DRESS IN CUT-OUT FABRIC',
        color: ['KHAKI'],
        image: 'assets/images/light-khaki-dress.jpg',
        description:
            'Midi dress with round neckline and long sleeves. Elastic beaded cutouts at the front, elasticated waistband. Back slit with button.',
        category: 'dresses',
        price: '89.99 USD',
        size: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
        brand: 'ZARA',
        quantity: 10,
        year: 2022,
        popular: true,
        id: 3,
    },
    {
        title: 'BLOUSE WITH PRINT WITH KNOT',
        color: ['KHAKI'],
        image: 'assets/images/ecru-shirt.jpg',
        description: 'Cropped blouse with V-neck and knot. Sleeves below the elbow.',
        category: 'shirts',
        price: '59.99 USD',
        size: ['XS', 'S', 'M', 'L', 'XL'],
        brand: 'H&M',
        quantity: 15,
        year: 2020,
        popular: true,
        id: 4,
    },
    {
        title: 'BLOUSE WITH OPENWORK EMBROIDERY',
        color: ['KHAKI'],
        image: 'assets/images/khaki-shirt.jpg',
        description:
            'Blouse with stand-up collar and long sleeves. Elastic hems, tone-on-tone openwork embroidery. Concealed zip fastening at the back.',
        category: 'shirts',
        price: '99.99 USD',
        size: ['S', 'M', 'L', 'XL'],
        brand: 'H&M',
        quantity: 17,
        year: 2021,
        popular: false,
        id: 5,
    },
    {
        title: 'POPLIN SHIRT',
        color: ['SAND'],
        image: 'assets/images/sand-shirt.jpg',
        description: 'Shirt with long sleeves and lapel collar. Front patch pocket and button fastening at the front.',
        category: 'shirts',
        price: '59.99 USD',
        size: ['S', 'M', 'L', 'XL', 'XXL'],
        brand: 'MANGO',
        quantity: 14,
        year: 2020,
        popular: true,
        id: 6,
    },
    {
        title: 'RUSTIC PANTS WITH FRINGING',
        color: ['WHITE'],
        image: 'assets/images/rustic-pants.jpg',
        description: 'Pants with a high waist and wide legs. Zipper and button closure.',
        category: 'pants',
        price: '79.99 USD',
        size: ['XS', 'S', 'M'],
        brand: 'H&M',
        quantity: 28,
        year: 2022,
        popular: true,
        id: 7,
    },
    {
        title: 'HIGH RISE CULOTTES',
        color: ['WHITE'],
        image: 'assets/images/white-culottes.jpg',
        description:
            'Cotton trousers with a high waist and wide legs. Ribbed seams, front welt pockets. Fastened with a zipper, inner button and metal hook.',
        category: 'pants',
        price: '79.99 USD',
        size: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
        brand: 'ZARA',
        quantity: 7,
        year: 2020,
        popular: true,
        id: 8,
    },
    {
        title: 'SHIRT WITH GOLD BUTTONS',
        color: ['SAND'],
        image: 'assets/images/light-beige-shirt.jpg',
        description:
            'Shirt with collar and long sleeves. Cuffs with cuffs, button-down straps. Front patch pockets. Fastened with golden buttons.',
        category: 'shirts',
        price: '69.99 USD',
        size: ['S', 'L', 'XL', 'XXL'],
        brand: 'MANGO',
        quantity: 17,
        year: 2019,
        popular: false,
        id: 9,
    },
    {
        title: 'JACKET WITH EMBROIDERY AND TASSES',
        color: ['SAND'],
        image: 'assets/images/jacket-with-tasses.jpg',
        description:
            'Jacket with a round neckline and wide sleeves below the elbow. Contrasting embroidery, tassels. Ties at the front.',
        category: 'shirts',
        price: '89.99 USD',
        size: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
        brand: 'ZARA',
        quantity: 10,
        year: 2022,
        popular: true,
        id: 10,
    },
    {
        title: 'JACQUARD TROUSERS IN PAJAMA STYLE',
        color: ['BLACK'],
        image: 'assets/images/jacquard-pants.jpg',
        description: 'Trousers in flowing fabric with a high waist and wide legs. Elasticated waist.',
        category: 'pants',
        price: '69.99 USD',
        size: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
        brand: 'ZARA',
        quantity: 23,
        year: 2022,
        popular: true,
        id: 11,
    },
    {
        title: 'ROLLED SHIRT',
        color: ['SAND'],
        image: 'assets/images/rolled-shirt.jpg',
        description: 'Shirt with collar and V-neck. Long sleeves with cuffs. Fastens with buttons.',
        category: 'shirts',
        price: '59.99 USD',
        size: ['XS', 'S', 'M', 'L', 'XXL'],
        brand: 'ZARA',
        quantity: 5,
        year: 2022,
        popular: true,
        id: 12,
    },
    {
        title: 'LINEN SHIRT WITH EMBROIDERY',
        color: ['SAND'],
        image: 'assets/images/yellow-white-shirt.jpg',
        description: 'Shirt in 100% linen. Collar, long sleeves with cuffs, embroidery. Fastens with buttons.',
        category: 'shirts',
        price: '79.99 USD',
        size: ['XS', 'M', 'L', 'XL', 'XXL'],
        brand: 'MANGO',
        quantity: 7,
        year: 2020,
        popular: true,
        id: 13,
    },
    {
        title: 'SHIRT WITH LACE CROCHET',
        color: ['MULTI-COLORED'],
        image: 'assets/images/milti-colored-shirt.jpg',
        description: 'V-neck shirt with short wide sleeves. Contrasting crochet lace detail.',
        category: 'shirts',
        price: '59.99 USD',
        size: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
        brand: 'ZARA',
        quantity: 17,
        year: 2021,
        popular: true,
        id: 14,
    },
    {
        title: 'PRINT SHIRT',
        color: ['MULTI-COLORED'],
        image: 'assets/images/print-shirt.jpg',
        description:
            'V-neck shirt with adjustable drawstrings in the same fabric. Wooden details, long sleeves. Cuffs with buttons.',
        category: 'shirts',
        price: '49.99 USD',
        size: ['S', 'M', 'L', 'XL', 'XXL'],
        brand: 'ZARA',
        quantity: 24,
        year: 2019,
        popular: true,
        id: 15,
    },
    {
        title: 'ROLLED SHIRT IN PRINTED FABRIC',
        color: ['MULTI-COLORED'],
        image: 'assets/images/rolled-print-shirt.jpg',
        description: 'Shirt with elastic collar, flounce and bow. V-neck, long sleeves. Elastic details.',
        category: 'shirts',
        price: '59.99 USD',
        size: ['XS', 'S', 'M', 'XL', 'XXL'],
        brand: 'H&M',
        quantity: 4,
        year: 2021,
        popular: false,
        id: 16,
    },
    {
        title: 'SATIN TIE DIE BLOUSE',
        color: ['MULTI-COLORED'],
        image: 'assets/images/satin-blouse.jpg',
        description: 'Flowy blouse. Collar, V-neckline and button. Long sleeves and an asymmetrical hem with a slit.',
        category: 'shirts',
        price: '89.99 USD',
        size: ['XS', 'S', 'M', 'XL', 'XXL'],
        brand: 'H&M',
        quantity: 30,
        year: 2022,
        popular: true,
        id: 17,
    },
    {
        title: 'SHIRT WITH OPENWORK EMBROIDERY',
        color: ['WHITE'],
        image: 'assets/images/white-shirt.jpg',
        description: 'Shirt with collar and long puff sleeves. Openwork embroidery in tone. Fastens with buttons.',
        category: 'shirts',
        price: '99.99 USD',
        size: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
        brand: 'H&M',
        quantity: 20,
        year: 2018,
        popular: true,
        id: 18,
    },
    {
        title: 'SHORT DRESS WITH EMBROIDERY',
        color: ['MULTI-COLORED', 'BLACK'],
        image: 'assets/images/short-black-dress.jpg',
        description:
            'Keyhole mini dress with adjustable ties. Long sleeves with elasticated cuffs. Contrasting embroidery. Side slits.',
        category: 'dresses',
        price: '119.00 USD',
        size: ['S', 'M', 'L', 'XL'],
        brand: 'H&M',
        quantity: 8,
        year: 2022,
        popular: true,
        id: 19,
    },
    {
        title: 'FLORAL PRINT CORSET DRESS',
        color: ['MULTI-COLORED'],
        image: 'assets/images/pink-dress.jpg',
        description:
            'Dress with a sweetheart neckline and adjustable thin shoulder straps. Gathered detail at the back, concealed zip fastening at the side.',
        category: 'dresses',
        price: '79.99 USD',
        size: ['S', 'M', 'L', 'XL'],
        brand: 'MANGO',
        quantity: 19,
        year: 2020,
        popular: true,
        id: 20,
    },
    {
        title: 'SHIRT WITH CONTRAST EMBROIDERY',
        color: ['WHITE'],
        image: 'assets/images/shirt-with-embroidery.jpg',
        description:
            'Shirt with collar and long sleeves. Front patch pocket. Details with openwork embroidery. Fastens with buttons.',
        category: 'shirts',
        price: '59.99 USD',
        size: ['S', 'M', 'L', 'XL', 'XXL'],
        brand: 'MANGO',
        quantity: 22,
        year: 2020,
        popular: true,
        id: 21,
    },
    {
        title: 'SHIRT WITH LACE CROCHET',
        color: ['WHITE'],
        image: 'assets/images/shirt-with-lace-crochet.jpg',
        description: 'Shirt with collar and long sleeves. Details in contrasting fabric, fastened with buttons.',
        category: 'shirts',
        price: '59.99 USD',
        size: ['XS', 'M', 'L', 'XL', 'XXL'],
        brand: 'MANGO',
        quantity: 19,
        year: 2021,
        popular: false,
        id: 22,
    },
    {
        title: 'BLOUSE IN CUPRO WITH LACE',
        color: ['BLACK'],
        image: 'assets/images/black-shirt.jpg',
        description:
            'High collar blouse in 100% cupro fabric. Long sleeves, matching lace details. Back slit with button.',
        category: 'shirts',
        price: '99.99 USD',
        size: ['M', 'L', 'XL', 'XXL'],
        brand: 'ZARA',
        quantity: 18,
        year: 2021,
        popular: true,
        id: 23,
    },
    {
        title: 'COTTON BLOUSE WITH EMBROIDERY',
        color: ['BLACK', 'MULTI-COLORED'],
        image: 'assets/images/black-cotton-blouse.jpg',
        description:
            'Blouse with round neckline and long sleeves. Embroidery, button closure. Drawstring adjustable hem.',
        category: 'shirts',
        price: '59.99 USD',
        size: ['S', 'M', 'L', 'XL', 'XXL'],
        brand: 'H&M',
        quantity: 8,
        year: 2022,
        popular: true,
        id: 24,
    },
    {
        title: 'BLOUSE WITH EMBROIDERY',
        color: ['BLACK', 'MULTI-COLORED'],
        image: 'assets/images/black-blouse.jpg',
        description:
            'Blouse with long sleeves and a V-shaped neckline. Embroidery, contrasting beads with a mirror finish. Fastened with buttons.',
        category: 'shirts',
        price: '99.99 USD',
        size: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
        brand: 'MANGO',
        quantity: 7,
        year: 2022,
        popular: true,
        id: 25,
    },
    {
        title: 'PRINT SHIRT',
        color: ['BLACK', 'MULTI-COLORED'],
        image: 'assets/images/print-black-shirt.jpg',
        description: 'Shirt with a collar and wide long sleeves. Side slits at the bottom. Fastens with buttons.',
        category: 'shirts',
        price: '99.99 USD',
        size: ['XS', 'S', 'L', 'XL', 'XXL'],
        brand: 'ZARA',
        quantity: 17,
        year: 2021,
        popular: true,
        id: 26,
    },
    {
        title: 'PRINT SHORT DRESS',
        color: ['KHAKI'],
        image: 'assets/images/green-dress.jpg',
        description: 'Short dress with V-neckline and adjustable ties. Sleeves below the elbow, frill at the bottom.',
        category: 'dresses',
        price: '89.99 USD',
        size: ['XS', 'S', 'M', 'L', 'XXL'],
        brand: 'MANGO',
        quantity: 20,
        year: 2021,
        popular: true,
        id: 27,
    },
    {
        title: 'MIDI DRESS WITH HALTER NECK',
        color: ['KHAKI'],
        image: 'assets/images/midi-green-dress.jpg',
        description:
            'Dress with a halter neckline and thin, adjustable shoulder straps at the back. Gathering on the sides.',
        category: 'dresses',
        price: '59.99 USD',
        size: ['XS', 'S', 'M', 'L'],
        brand: 'H&M',
        quantity: 5,
        year: 2022,
        popular: true,
        id: 28,
    },
    {
        title: 'PLEATED MIDI DRESS',
        color: ['KHAKI'],
        image: 'assets/images/aquamarine-dress.jpg',
        description:
            'Dress with a round neckline and short sleeves. Lining, elastic waistband. Fastened with a button on the back.',
        category: 'dresses',
        price: '119.00 USD',
        size: ['S', 'M', 'L'],
        brand: 'ZARA',
        quantity: 15,
        year: 2020,
        popular: true,
        id: 29,
    },
    {
        title: 'LINEN BLENDED DRESS WITH RHINES',
        color: ['SAND'],
        image: 'assets/images/light-sand-dress.jpg',
        description:
            'Linen-blend midi dress. Square neckline, thin shoulder straps with rhinestones. Elastic side slits, concealed zip fastening at the back.',
        category: 'dresses',
        price: '99.99 USD',
        size: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
        brand: 'MANGO',
        quantity: 30,
        year: 2022,
        popular: true,
        id: 30,
    },
    {
        title: 'LINEN BLEND DRESS',
        color: ['SAND'],
        image: 'assets/images/sand-dress.jpg',
        description:
            'Jumpsuit in linen fabric with round neckline and short sleeves with cuffs. Side pockets, chest patch pockets, trouser legs with elasticated sides. Fastened with buttons at the front.',
        category: 'dresses',
        price: '119.00 USD',
        size: ['XS', 'M', 'L', 'XL', 'XXL'],
        brand: 'H&M',
        quantity: 23,
        year: 2021,
        popular: true,
        id: 31,
    },
    {
        title: 'KNITTED DRESS WITHOUT SLEEVES',
        color: ['SAND'],
        image: 'assets/images/ecru-dress.jpg',
        description: 'Sleeveless dress with high collar and lapel.',
        category: 'dresses',
        price: '79.99 USD',
        size: ['XS', 'M', 'L', 'XL'],
        brand: 'ZARA',
        quantity: 13,
        year: 2022,
        popular: true,
        id: 32,
    },
    {
        title: 'DRESS WITH GEOMETRIC PRINT',
        color: ['MULTI-COLORED'],
        image: 'assets/images/multi-colored-dress.jpg',
        description: 'Mini dress with a high collar and short sleeves. Cutout with button at the back.',
        category: 'dresses',
        price: '89.99 USD',
        size: ['M', 'L', 'XL'],
        brand: 'MANGO',
        quantity: 23,
        year: 2022,
        popular: true,
        id: 33,
    },
    {
        title: 'PRINT DRESS',
        color: ['MULTI-COLORED'],
        image: 'assets/images/print-multi-colored-dress.jpg',
        description:
            'Dress with a round neck and a V-neck with a flounce. Long sleeves with elastic cuffs. Gathered waist, lined. Fastens with buttons.',
        category: 'dresses',
        price: '199.00 USD',
        size: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
        brand: 'H&M',
        quantity: 23,
        year: 2021,
        popular: true,
        id: 34,
    },
    {
        title: 'LEGGINGS WITH BRILLIANT LAMPS',
        color: ['BLACK'],
        image: 'assets/images/black-leggings.jpg',
        description: 'Leggings with a high waist and elasticated waist. Stripes with contrasting rhinestones.',
        category: 'pants',
        price: '69.99 USD',
        size: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
        brand: 'H&M',
        quantity: 13,
        year: 2021,
        popular: true,
        id: 35,
    },
    {
        title: 'POPLIN DRESS WITH ELASTIC WAIST',
        color: ['WHITE'],
        image: 'assets/images/poplin-dress.jpg',
        description:
            'Long wrap dress. Gathered short sleeves, elasticated cuffs. Elastic waistband with drawstrings at the sides.',
        category: 'dresses',
        price: '99.99 USD',
        size: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
        brand: 'ZARA',
        quantity: 18,
        year: 2021,
        popular: true,
        id: 36,
    },
    {
        title: 'ROLLED LINEN BLEND DRESS',
        color: ['WHITE'],
        image: 'assets/images/short-white-dress.jpg',
        description:
            'V-neck mini dress with thin straps. Ruffled hem, elastic gathered details. Concealed zip fastening at the back.',
        category: 'dresses',
        price: '89.99 USD',
        size: ['XS', 'M', 'L', 'XL', 'XXL'],
        brand: 'MANGO',
        quantity: 26,
        year: 2020,
        popular: true,
        id: 37,
    },
    {
        title: 'LEGGINGS WITH GOLD BUTTONS',
        color: ['BLACK'],
        image: 'assets/images/leggings.jpg',
        description: 'High rise leggings. Elastic waistband, raised seams. Decorative golden buttons.',
        category: 'pants',
        price: '39.99 USD',
        size: ['S', 'L', 'XL'],
        brand: 'ZARA',
        quantity: 11,
        year: 2019,
        popular: true,
        id: 38,
    },
    {
        title: 'MIDI SHIRT DRESS',
        color: ['WHITE'],
        image: 'assets/images/midi-shirt-dress.jpg',
        description:
            'Linen and cotton blend dress. Collar, short sleeves with cuffs. Front patch pockets, on-seam side pockets. Contrasting woven belt, slits at the bottom. Fastened with buttons.',
        category: 'dresses',
        price: '119.00 USD',
        size: ['XS', 'M', 'L', 'XXL'],
        brand: 'ZARA',
        quantity: 6,
        year: 2018,
        popular: true,
        id: 39,
    },
    {
        title: 'DRESS WITH ROLLS AND PLUMETI EMBROIDERY',
        color: ['WHITE'],
        image: 'assets/images/dress-with-rolls.jpg',
        description:
            'V-neck mini dress with decorative buttons. Wide shoulder straps with flounces, assemblies. Frill at the bottom, hidden zip fastening at the back.',
        category: 'dresses',
        price: '99.99 USD',
        size: ['XS', 'M', 'L'],
        brand: 'MANGO',
        quantity: 16,
        year: 2022,
        popular: true,
        id: 40,
    },
    {
        title: 'CUT-OUT SATIN DRESS',
        color: ['BLACK'],
        image: 'assets/images/satin-black-dress.jpg',
        description:
            'V-neck midi dress with thin crossover straps with adjustable ties at the back. Side slits, hidden side zip fastening.',
        category: 'dresses',
        price: '79.99 USD',
        size: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
        brand: 'H&M',
        quantity: 11,
        year: 2022,
        popular: true,
        id: 41,
    },
    {
        title: 'MINI DRESS',
        color: ['BLACK'],
        image: 'assets/images/black-dress.jpg',
        description: 'Short dress with round neckline and short sleeves. Fastens with a hidden zip at the back.',
        category: 'dresses',
        price: '99.99 USD',
        size: ['XS', 'S', 'L', 'XL', 'XXL'],
        brand: 'H&M',
        quantity: 14,
        year: 2022,
        popular: true,
        id: 42,
    },
    {
        title: 'MINI DRESS WITH BEADS',
        color: ['BLACK'],
        image: 'assets/images/dress-with-beads.jpg',
        description:
            'Linen blend dress. Square neckline with beading, adjustable thin shoulder straps. Gathered sides, concealed zip fastening at the back.',
        category: 'dresses',
        price: '89.99 USD',
        size: ['XS', 'S', 'L', 'XL'],
        brand: 'ZARA',
        quantity: 17,
        year: 2022,
        popular: true,
        id: 43,
    },
    {
        title: 'STRAIGHT PANTS WITH POCKETS',
        color: ['KHAKI'],
        image: 'assets/images/khaki-pants.jpg',
        description:
            'Pants with a high waist and straight legs. Front patch pockets, back patch pockets with flaps. Zipper and button closure.',
        category: 'pants',
        price: '79.99 USD',
        size: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
        brand: 'ZARA',
        quantity: 15,
        year: 2021,
        popular: true,
        id: 44,
    },
    {
        title: 'CARGO PANTS WITH BELT',
        color: ['KHAKI'],
        image: 'assets/images/cargo-pants.jpg',
        description:
            'Pants with a high waist. Pintucks, matching belt. Front pockets, side flap pockets. Decorative back pockets with flaps, zip fastening and metal hook.',
        category: 'pants',
        price: '69.99 USD',
        size: ['XS', 'M', 'L', 'XL', 'XXL'],
        brand: 'MANGO',
        quantity: 16,
        year: 2021,
        popular: false,
        id: 45,
    },
    {
        title: 'ZW THE MERCER JOGGING JEANS',
        color: ['KHAKI'],
        image: 'assets/images/light-khaki-pants.jpg',
        description:
            'Mid-rise jeans. Worn-effect fabric, elastic waistband at the back. Five pockets, elasticated cuffs. Zipper and button closure.',
        category: 'pants',
        price: '69.99 USD',
        size: ['M', 'L', 'XL', 'XXL'],
        brand: 'H&M',
        quantity: 6,
        year: 2021,
        popular: false,
        id: 46,
    },
    {
        title: 'FULL LENGTH PANTS',
        color: ['KHAKI'],
        image: 'assets/images/pastel-green-pants.jpg',
        description:
            'Pants with a high waist. Side pockets, decorative welted back pockets. Tucks in front, fastens with a zip and button at the top.',
        category: 'pants',
        price: '79.99 USD',
        size: ['M', 'L', 'XXL'],
        brand: 'ZARA',
        quantity: 19,
        year: 2021,
        popular: true,
        id: 47,
    },
    {
        title: 'CULOTTES WITH PLEAT',
        color: ['SAND'],
        image: 'assets/images/sand-pants.jpg',
        description: 'Wide-leg pants with a high waist and elasticated waist.',
        category: 'pants',
        price: '69.99 USD',
        size: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
        brand: 'MANGO',
        quantity: 9,
        year: 2018,
        popular: true,
        id: 48,
    },
    {
        title: 'HIGH RISE STRAIGHT PANTS',
        color: ['WHITE'],
        image: 'assets/images/natural-pants.jpg',
        description:
            'Pants with a high waist and straight legs. Front welt pockets. Zip closure, inner button and metal hook.',
        category: 'pants',
        price: '79.99 USD',
        size: ['XS', 'S', 'M', 'XL', 'XXL'],
        brand: 'H&M',
        quantity: 8,
        year: 2022,
        popular: true,
        id: 49,
    },
    {
        title: 'LONG PANTS WITH BUTTONS',
        color: ['WHITE'],
        image: 'assets/images/long-white-pants.jpg',
        description:
            'Trousers in a linen and cotton blend with a high waist and wide legs. Five pockets. Fastened with buttons.',
        category: 'pants',
        price: '79.99 USD',
        size: ['XS', 'S', 'M', 'XL'],
        brand: 'ZARA',
        quantity: 18,
        year: 2021,
        popular: true,
        id: 50,
    },
    {
        title: 'STANDARD-LENGTH FAUX LEATHER PANTS',
        color: ['WHITE'],
        image: 'assets/images/ecru-pants.jpg',
        description:
            'Pants with a high waist. Side pockets, decorative welt back pockets. Raised seams. Zip closure, inner button and metal hooks.',
        category: 'pants',
        price: '79.99 USD',
        size: ['XS', 'S', 'M', 'XL'],
        brand: 'MANGO',
        quantity: 16,
        year: 2020,
        popular: true,
        id: 51,
    },
    {
        title: 'HIGH RISE TROUSERS',
        color: ['MULTI-COLORED'],
        image: 'assets/images/multi-colored-pants.jpg',
        description:
            'Skinny trousers with a high waist. Ribbed seams, front welt pockets. Zip closure, metal hook and inner button.',
        category: 'pants',
        price: '79.99 USD',
        size: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
        brand: 'MANGO',
        quantity: 17,
        year: 2021,
        popular: false,
        id: 52,
    },
    {
        title: 'PRINTED FLARED PANTS',
        color: ['MULTI-COLORED'],
        image: 'assets/images/flared-pants.jpg',
        description:
            'Pants with a high waist, elastic waistband and slightly flared legs. Fastened with a zipper and a button.',
        category: 'pants',
        price: '69.99 USD',
        size: ['XS', 'S', 'M', 'L', 'XL'],
        brand: 'H&M',
        quantity: 27,
        year: 2022,
        popular: true,
        id: 53,
    },
    {
        title: 'PAJAMA PANTS WITH PRINT',
        color: ['MULTI-COLORED'],
        image: 'assets/images/pajama-pants.jpg',
        description: 'Pants with a high waist and laces. Elasticated waistband at the back, front pockets.',
        category: 'pants',
        price: '79.99 USD',
        size: ['XS', 'S', 'M', 'L'],
        brand: 'ZARA',
        quantity: 7,
        year: 2020,
        popular: true,
        id: 54,
    },
    {
        title: 'PANTS WITH ROLL WAIST WITH OPENWORK EMBROIDERY',
        color: ['BLACK'],
        image: 'assets/images/black-pants.jpg',
        description: 'Pants with a high waist and straight legs. Elastic waistband with adjustable drawstring.',
        category: 'pants',
        price: '79.99 USD',
        size: ['S', 'M', 'L'],
        brand: 'MANGO',
        quantity: 3,
        year: 2019,
        popular: true,
        id: 55,
    },
    {
        title: 'SLIGHTLY FLARED SATIN PANTS',
        color: ['BLACK'],
        image: 'assets/images/flared-satin-pants.jpg',
        description: 'Pants with a high waist. Zip fastening and matching covered button.',
        category: 'pants',
        price: '59.99 USD',
        size: ['S', 'M', 'L', 'XL', 'XXL'],
        brand: 'MANGO',
        quantity: 13,
        year: 2019,
        popular: true,
        id: 56,
    },
    {
        title: 'FLAT PANTS',
        color: ['BLACK'],
        image: 'assets/images/flat-pants.jpg',
        description: 'High rise flared trousers. Fastened with a zip and a button at the front.',
        category: 'pants',
        price: '39.99 USD',
        size: ['S', 'L', 'XL', 'XXL'],
        brand: 'H&M',
        quantity: 19,
        year: 2022,
        popular: true,
        id: 57,
    },
    {
        title: 'FLOWER PRINT DRESS',
        color: ['MULTI-COLORED'],
        image: 'assets/images/flower-dress.jpg',
        description:
            'Linen blend dress. Halter neckline, cutout at the waist, side pleats. Open back. Fastens with matching buttons and a hidden zip.',
        category: 'dresses',
        price: '89.99 USD',
        size: ['XS', 'S', 'M', 'L', 'XL'],
        brand: 'ZARA',
        quantity: 3,
        year: 2022,
        popular: true,
        id: 58,
    },
    {
        title: 'LINEN TIE DIE DRESS',
        color: ['MULTI-COLORED'],
        image: 'assets/images/tie-die-dress.jpg',
        description: 'Dress with a draped neckline. Thin straps crossed at the back with a bow.',
        category: 'dresses',
        price: '99.99 USD',
        size: ['S', 'M', 'L', 'XL'],
        brand: 'MANGO',
        quantity: 28,
        year: 2022,
        popular: true,
        id: 59,
    },
    {
        title: 'LEGGINGS WITH WIDE WAIST DETAILS',
        color: ['BLACK'],
        image: 'assets/images/leggings-with-details.jpg',
        description: 'High rise leggings. Wide elastic waistband.',
        category: 'pants',
        price: '39.99 USD',
        size: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
        brand: 'H&M',
        quantity: 12,
        year: 2022,
        popular: false,
        id: 60,
    },
];

export default cards;
